Fixed Extra Messages After Vote
Arechii/CallVote pull request #7
Opened 2020-12-31 11:14 UTC by Cyphierion117

Fixed code which originally caused an issue with additional success/failure messages being sent after a vote.

2020-12-31 17:07 UTC, Arechii requested changes
Thank you for the pull request! I've left some comments that should be addressed before the merge.

2020-12-31 17:07 UTC, Arechii commented on IVote.cs
> +
This should not be enforced by the interface since third party vote implementations could use tasks instead of coroutines for example to handle cooldowns and such.

2020-12-31 17:07 UTC, Arechii commented on Vote.cs
> +
Perhaps these should be private and named properly?
```suggestion
        private Coroutine _startCoroutine;

        private Coroutine _cooldownCoroutine;

```

2020-12-31 17:07 UTC, Arechii commented on Vote.cs
> +            thisCoroutine1 = Plugin.Instance.StartCoroutine(Start());
```suggestion
            _startCoroutine = Plugin.Instance.StartCoroutine(Start());
```

2020-12-31 17:07 UTC, Arechii commented on Vote.cs
> +            Plugin.Instance.StopCoroutine(thisCoroutine1);
```suggestion
            Plugin.Instance.StopCoroutine(_startCoroutine);
```

2020-12-31 17:07 UTC, Arechii commented on Vote.cs
> +            Plugin.Instance.StopCoroutine(thisCoroutine1);
```suggestion

            _cooldownCoroutine = Plugin.Instance.StartCoroutine(Cooldown(Settings.CooldownTime));

            Plugin.Instance.StopCoroutine(_startCoroutine);
```

2021-01-01 02:48 UTC, Cyphierion117 commented
I resolved your requested changes in the project and requested a re-review. Thank you for your time :)

2021-01-01 03:07 UTC, Arechii commented
Thanks!

2021-01-01 03:07 UTC, merged